plugins {
    id 'java'
}

version = '2.18.0'

repositories {
    mavenCentral()
}

/*dependencies {
    implementation 'commons-io:commons-io:2.6'
}*/

tasks.register('uberJar', Jar) {
    archiveClassifier = 'uber'

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

jar {
    manifest {
        attributes("Implementation-Title": "Temperature Converter",
                   "Implementation-Version": archiveVersion,
                   "Main-Class": "net.localarea.doug.tempcon.Main")
    }
}

//tasks.named('jar') { manifest.writeTo(layout.buildDirectory.file('mymanifest.mf')) }

