plugins {
    id 'java'
    id 'application'
    id 'eclipse' // generate Eclipse project files

    // test logger plugin for colorful CLI test output
    // https://github.com/radarsh/gradle-test-logger-plugin
    id 'com.adarshr.test-logger' version '4.0.0'
}

repositories {
    mavenCentral()
}

dependencies {
    //implementation 'commons-io:commons-io:2.6'

    // JUnit Jupiter (aggregated)
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams=true // enable stdout & stderr
}

tasks.register('uberJar', Jar) {
    archiveClassifier = 'uber'

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

task populateVersion {
    def versionFile = file('version.txt')
    if (!versionFile.exists()) {
        versionFile.text = '0.0.0' // dummy version if file not found
    }
    // set project version
    project.version = versionFile.text.trim()
}

jar {
    manifest {
        attributes("Implementation-Title": "Temperature Converter",
                   "Implementation-Version": project.version,
                   "Main-Class": "net.localarea.doug.tempcon.Main")
    }
}

task runJar(type: JavaExec, dependsOn: jar) {
    group = 'application'
    description = 'Run the application'
    classpath = files(jar.archiveFile)
    mainClass = 'net.localarea.doug.tempcon.Main'
}
