plugins {
    id 'java'
    id 'eclipse' // generate Eclipse project files

    // test logger plugin for colorful CLI test output
    // https://github.com/radarsh/gradle-test-logger-plugin
    id 'com.adarshr.test-logger' version '4.0.0'
}

version = '2.18.2'

repositories {
    mavenCentral()
}

dependencies {
    //implementation 'commons-io:commons-io:2.6'

    // JUnit Jupiter (aggregated)
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams=true // enable stdout & stderr
}

tasks.register('uberJar', Jar) {
    archiveClassifier = 'uber'

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

jar {
    manifest {
        attributes("Implementation-Title": "Temperature Converter",
                   "Implementation-Version": archiveVersion,
                   "Main-Class": "net.localarea.doug.tempcon.Main")
    }
}

//tasks.named('jar') { manifest.writeTo(layout.buildDirectory.file('mymanifest.mf')) }

